### PR TITLE
Update Whale ASCII art

### PR DESCRIPTION
**Pull request by thaJeztah**
The logo was updated recently and no longer
has the "waves".

This patch removes the waves from the ASCII art
to better match the new logo design.

ping @bfirsh @tianon PTAL :)

### CODE REVIEW

**Comment by bfirsh** [comment]
My you have such big eyes, moby.

LGTM. :)

**Comment by tianon** [comment]
lol, LGTM

I think boot2docker still has one of these embedded somewhere (or multiple somewheres) too. :sweat_smile:

**Comment by thaJeztah** [comment]
Oh, yes, I should dive into boot2docker as well lol

**Comment by thaJeztah** [comment]
> My you have such big eyes, moby.

Subtle; I liked a slightly bigger eye 😇

**Pull request merged**
